### ISSUE TITLE
mes addが失敗する

### ISSUE THREAD

**Issue by tawashichan** [matsuri-tech/endpoints-sdk-cli#12]
<img width="753" alt="スクリーンショット 2020-02-19 13 34 27" src="https://user-images.githubusercontent.com/31276400/74802240-9b6ca600-531c-11ea-8b63-6778c1b49ba2.png">

- バージョン情報
  - endpoints-sdk-cli/2.0.2 darwin-x64 node-v13.3.0 

- 手順
  - 下記の順でコマンドを入力
  - npm install -g endpoints-sdk-cli
  - mes add https://github.com/matsuri-tech/m2m-users

**Comment by tawashichan** [comment]
globalで入れて使ってはいけないということでしたが,usageの修正が必要という認識で合っていますか？
https://github.com/matsuri-tech/endpoints-sdk-cli#usage

**Comment by hrdtbs** [comment]
usage自動生成されるんですよね...

**Comment by tawashichan** [comment]
悲しい

**Comment by hrdtbs** [comment]
原因は分かっているので治せるんですが、それとは別にそもそもglobalにいれてほしくないので、usageどうにかしたい...

**Comment by tawashichan** [comment]
あれ,
1. npm uninstall -g endpoints-sdk-cli
2. yarn add endpoints-sdk-cli
3. yarn run mes add https://github.com/matsuri-tech/m2m-users.git

と実行したんですが,
<img width="994" alt="スクリーンショット 2020-02-19 14 58 32" src="https://user-images.githubusercontent.com/31276400/74806073-50f12680-5328-11ea-8e04-712de875d1fe.png">

同様のエラーが出ますね...(そもそもmesの実行の仕方合っているんだろうか...)

**Comment by hrdtbs** [comment]
まずglobalのendpoints-sdk-cliをアンインストールして、

```
$ yarn add endpoints-sdk-cli -D
$ mes add ~
```

でいけるはずです。

**Comment by hrdtbs** [comment]
v2.0.4で解消済み
