### ISSUE TITLE
endpointの更新が出来ない

### ISSUE THREAD

**Issue by myuon** [matsuri-tech/endpoints-sdk-cli#16]
mesで事前にendpointsファイルを生成しているとき、

## 1. updateコマンド
- `mes update` や `mes update hoge` とすると次のようなエラーになる

```
 ›   Error: The service does not exist in the dependency. Check dependencies property of the endpoints.config.json. Or use the add
 ›   command to add dependencies before installing
```

## 2. installコマンド

- `mes add ...` で最新バージョンに更新(endpoints.config.jsonは更新された)
- `mes install` すると、成功するがファイルの上書きは行なわれない(これは期待する動作といえば動作だが、ファイルがすでにあるから上書きはしないという警告くらいはほしい)

**Comment by myuon** [comment]
installコマンドの方は勘違いの可能性が高い気がしてきた
(そもそもendpoints.jsonの取得が上手くいっていないかもしれない)

**Comment by hrdtbs** [comment]
>  ›   Error: The service does not exist in the dependency. Check dependencies property of the endpoints.config.json. Or use the add
 ›   command to add dependencies before installing

このエラーは.endpoints.config.jsonのdependenciesに記載のないendpointをインストールしようした場合に吐かれます

```json
{
  "dependencies": {
    "m2m-cleaning": { // ←これ
      "version": "9555cfab4888123b5ea8dafdf64dca3ef3258bec",
      "repository": "git@github.com:matsuri-tech/m2m-cleaning.git"
    },
    "m2mcheckin-backend": { // ←これ
      "version": "45dc16e217151a59c43b5599b78424d182e4dc71",
      "repository": "git@github.com:matsuri-tech/m2mcheckin-backend.git",
      "workspaces": [
        "go"
      ]
    }
  }
}
```

> mes install すると、成功するがファイルの上書きは行なわれない(これは期待する動作といえば動作だが、ファイルがすでにあるから上書きはしないという警告くらいはほしい)

`mes install`はendpoints.config.jsonからendpointsファイルを生成するだけなので、この挙動は正しいです。READMEにも書いてあるはず。

**Comment by myuon** [comment]
状態としてはconfigを変更しコミットハッシュが変わっているにもかかわらず、APIが追加されていないという問題です
(サブコマンド問わず、ファイル消しても変わらず)

**Comment by myuon** [comment]
mesの問題ではないことがわかった
