### ISSUE TITLE
endpoints.config.jsonで絶対パスを使わないようにする

### ISSUE THREAD

**Issue by myuon** [matsuri-tech/endpoints-sdk-cli#27]
outputにendpointsの絶対パスが表示されているが、`/home/[username]` のように環境依存の値になってしまっているためお行儀が悪い&mes addが動かないため相対パスで入れるようにしてほしい

**Comment by hrdtbs** [comment]
実装ミスじゃん...以前は大丈夫だったと思うのでバージョンあげるときにバグ挿入したっぽいですね
